# Generated by Django 5.0.3 on 2025-12-03 10:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "vin",
                    models.CharField(
                        db_column="VIN",
                        max_length=150,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "car_status",
                    models.CharField(
                        choices=[
                            ("заказан", "Заказан"),
                            ("на заводе", "На заводе"),
                            ("в пути", "В пути"),
                            ("прибыл", "Прибыл"),
                            ("в продаже", "В продаже"),
                            ("для тест-драйвов", "Для тест-драйвов"),
                            ("продан", "Продан"),
                        ],
                        db_column="Статус_автомобиля",
                        default="заказан",
                        max_length=100,
                    ),
                ),
                ("make", models.CharField(db_column="Марка", max_length=50)),
                ("model", models.CharField(db_column="Модель", max_length=50)),
                ("engine", models.CharField(db_column="Двигатель", max_length=50)),
                ("gearbox", models.CharField(db_column="Коробка", max_length=50)),
                ("driven_wheels", models.CharField(db_column="Привод", max_length=50)),
                ("body", models.CharField(db_column="Кузов", max_length=50)),
                ("make_year", models.IntegerField(db_column="Год_производства")),
                ("trim", models.CharField(db_column="Комплектация", max_length=50)),
                (
                    "addons",
                    models.CharField(
                        blank=True,
                        db_column="Дополнительное_оборудование",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("color", models.CharField(db_column="Цвет", max_length=50)),
                (
                    "date_of_delivery",
                    models.DateField(
                        blank=True, db_column="Дата_поступления", null=True
                    ),
                ),
                ("price", models.IntegerField(db_column="Цена")),
                (
                    "discount",
                    models.IntegerField(
                        blank=True, db_column="Скидка", default=0, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Автомобиль",
                "verbose_name_plural": "Автомобили",
                "db_table": "Автомобиль",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "passport_client",
                    models.BigIntegerField(
                        db_column="Паспорт_клиент", primary_key=True, serialize=False
                    ),
                ),
                ("fio", models.CharField(db_column="ФИО", max_length=100)),
                (
                    "license_number",
                    models.BigIntegerField(
                        blank=True, db_column="Номер_ву", null=True, unique=True
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(db_column="Номер_телефона", max_length=50),
                ),
                ("b_day", models.DateField(db_column="Дата_рождения")),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
                "db_table": "Клиент",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id_employee",
                    models.AutoField(
                        db_column="idСотрудника", primary_key=True, serialize=False
                    ),
                ),
                ("fio", models.CharField(db_column="ФИО", max_length=100)),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("менеджер", "Менеджер"),
                            ("продавец-консультант", "Продавец-консультант"),
                            ("сервис", "Сотрудник сервиса"),
                            ("закупки", "Специалист по закупкам"),
                        ],
                        db_column="Должность",
                        max_length=50,
                    ),
                ),
                (
                    "phone_number",
                    models.BigIntegerField(db_column="Номер_телефона", unique=True),
                ),
                (
                    "license_number",
                    models.BigIntegerField(
                        blank=True, db_column="Номер_ву", null=True, unique=True
                    ),
                ),
                (
                    "passport_employee",
                    models.BigIntegerField(db_column="Паспорт_сотрудник", unique=True),
                ),
                ("b_date", models.DateField(db_column="Дата_рождения")),
                ("employed", models.IntegerField(db_column="Трудоустроен", default=1)),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
                "db_table": "Сотрудник",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id_order",
                    models.AutoField(
                        db_column="idЗаказа", primary_key=True, serialize=False
                    ),
                ),
                (
                    "date_order",
                    models.DateField(auto_now_add=True, db_column="Дата_заказа"),
                ),
                (
                    "state_order",
                    models.CharField(
                        db_column="Статус_заказа", default="Заказан", max_length=100
                    ),
                ),
                ("make", models.CharField(db_column="Марка", max_length=50)),
                ("model", models.CharField(db_column="Модель", max_length=50)),
                ("engine", models.CharField(db_column="Двигатель", max_length=50)),
                ("gearbox", models.CharField(db_column="Коробка", max_length=50)),
                ("driven_wheels", models.CharField(db_column="Привод", max_length=50)),
                ("body", models.CharField(db_column="Кузов", max_length=50)),
                ("make_year", models.IntegerField(db_column="Год_производства")),
                ("trim", models.CharField(db_column="Комплектация", max_length=50)),
                (
                    "addons",
                    models.CharField(
                        db_column="Дополнительное_оборудование", max_length=200
                    ),
                ),
                ("amount", models.IntegerField(db_column="Количество", default=1)),
                ("expected_delivery", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "db_table": "Заказ",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id_sale",
                    models.AutoField(
                        db_column="idПродажи", primary_key=True, serialize=False
                    ),
                ),
                (
                    "sale_date",
                    models.DateField(
                        db_column="Дата_продажи", default=django.utils.timezone.now
                    ),
                ),
                (
                    "end_price",
                    models.BigIntegerField(db_column="Итоговая_сумма", default=0),
                ),
            ],
            options={
                "verbose_name": "Продажа",
                "verbose_name_plural": "Продажи",
                "db_table": "Продажа",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Test_drive",
            fields=[
                (
                    "id_test",
                    models.AutoField(
                        db_column="idТест_драйва", primary_key=True, serialize=False
                    ),
                ),
                (
                    "datetime_reservation",
                    models.DateTimeField(db_column="ДатаВремя_брони"),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True, db_column="Итог", max_length=20, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Тест-драйв",
                "verbose_name_plural": "Тест-драйвы",
                "db_table": "Тест_драйв",
                "managed": True,
            },
        ),
        migrations.AddConstraint(
            model_name="car",
            constraint=models.CheckConstraint(
                check=models.Q(("price__gt", 100000)), name="price_gt_100k"
            ),
        ),
        migrations.AddConstraint(
            model_name="car",
            constraint=models.CheckConstraint(
                check=models.Q(("discount__lte", 50)), name="discount_lte_50"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="id_employee",
            field=models.ForeignKey(
                db_column="idСотрудника",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.employee",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="ip_employee",
            field=models.ForeignKey(
                db_column="idСотрудника",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.employee",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="passport_client",
            field=models.ForeignKey(
                db_column="Паспорт_клиент",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.client",
            ),
        ),
        migrations.AddField(
            model_name="test_drive",
            name="id_employee",
            field=models.ForeignKey(
                db_column="idСотрудника",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.employee",
            ),
        ),
        migrations.AddField(
            model_name="test_drive",
            name="passport_client",
            field=models.ForeignKey(
                db_column="Паспорт_клиент",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.client",
            ),
        ),
        migrations.AddField(
            model_name="test_drive",
            name="vin",
            field=models.ForeignKey(
                db_column="VIN",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.car",
            ),
        ),
        migrations.CreateModel(
            name="Sale_list",
            fields=[
                (
                    "id_sale",
                    models.OneToOneField(
                        db_column="idПродажи",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="core.sale",
                    ),
                ),
                (
                    "discounted_prise",
                    models.BigIntegerField(db_column="Цена_со_скидкой"),
                ),
                (
                    "vin",
                    models.ForeignKey(
                        db_column="VIN",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.car",
                    ),
                ),
            ],
            options={
                "verbose_name": "Состав продажи",
                "verbose_name_plural": "Состав продаж",
                "db_table": "Состав_продажи",
                "managed": True,
                "unique_together": {("id_sale", "vin")},
            },
        ),
    ]
